name: Build EXE

permissions:
  contents: read

on: [push, workflow_dispatch]

jobs:
  upload-exe:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cache LLVM Installer
        id: cache-llvm
        uses: actions/cache@v4
        with:
          path: LLVM-21.1.6-win32.exe
          key: llvm-installer-21.1.6
      - name: Download LLVM Installer
        if: steps.cache-llvm.outputs.cache-hit != 'true'
        run: |
          curl -L -o LLVM-21.1.6-win32.exe https://github.com/llvm/llvm-project/releases/download/llvmorg-21.1.6/LLVM-21.1.6-win32.exe
      - name: Install LLVM
        shell: pwsh
        run: |
          $p = Start-Process -FilePath ".\LLVM-21.1.6-win32.exe" -ArgumentList "/S" -PassThru
          $p.WaitForExit()
      - name: Build EXE
        shell: cmd
        run: |
          "C:\\Program Files (x86)\\LLVM\\bin\\clang" test.cc -fno-exceptions && a.exe && build.llvm.bat

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pefile
          python postlink.py

      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: exe
          path: persian-calendar.exe

  ubuntu-continue:
    needs: upload-exe
    runs-on: ubuntu-latest
    steps:
      - name: Download EXE artifact
        uses: actions/download-artifact@v4
        with:
          name: exe
          path: ./downloaded-exe

      - name: Show downloaded files
        run: |
          ls -la downloaded-exe
          file downloaded-exe/persian-calendar.exe || true

      - name: Notify
        env:
          COMMITS: ${{ toJson(github.event.commits) }}
          TEMPLATE: '.[] | "<a href=\"\(.url)\">\(.id[:8])</a> â€¢ <a href=\"https://github.com/\(.author.username | @html)\">\(.author.username | @html)</a>

          \(.message | gsub("(?<a>[<>&\"])"; .a|@html))

          "'
        run: |
          # Upload the file
          MESSAGE_ID=$(
            curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendDocument" \
              -F chat_id="${{ secrets.TELEGRAM_CHAT_ID }}" \
              -F document=@"downloaded-exe/persian-calendar.exe" | jq '.result.message_id'
          )

          # Edit the post description
          (
            printenv COMMITS | jq -r "$TEMPLATE"
            printf "%s\n\n" "$(stat -c%s downloaded-exe/persian-calendar.exe) bytes"
            printf 'ðŸ“… @Persian_Calendar (win32)'
          ) | \
          jq -R --slurp --argjson mid "$MESSAGE_ID" '{
            caption: .,
            message_id: $mid,
            chat_id: "${{ secrets.TELEGRAM_CHAT_ID }}",
            parse_mode: "HTML"
          }' | \
          curl -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/editMessageCaption \
            -H 'Content-Type: application/json' \
            --data-binary @-
