name: Build EXE

permissions:
  contents: read

on: [push, workflow_dispatch]

jobs:
  upload-exe:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build EXE
        shell: cmd
        run: "\"C:\\Program Files\\Microsoft Visual Studio\\2022\\Enterprise\\VC\\Auxiliary\\Build\\vcvarsall.bat\" x86 && cl test.cc && test.exe && build.bat"
      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: exe
          path: persian-calendar.exe

  ubuntu-continue:
    needs: upload-exe
    runs-on: ubuntu-latest
    steps:
      - name: Download EXE artifact
        uses: actions/download-artifact@v4
        with:
          name: exe
          path: ./downloaded-exe

      - name: Show downloaded files
        run: |
          ls -la downloaded-exe
          file downloaded-exe/persian-calendar.exe || true

      - name: Notify
        env:
          COMMITS: ${{ toJson(github.event.commits) }}
          TEMPLATE: '.[] | "<a href=\"\(.url)\">\(.id[:8])</a> â€¢ <a href=\"https://github.com/\(.author.username | @html)\">\(.author.username | @html)</a>

          \(.message | gsub("(?<a>[<>&\"])"; .a|@html))

          "'
        run: |
          # Upload the file
          MESSAGE_ID=$(
            curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendDocument" \
              -F chat_id="${{ secrets.TELEGRAM_CHAT_ID }}" \
              -F document=@"downloaded-exe/persian-calendar.exe" | jq '.result.message_id'
          )

          # Edit the post description
          (
            printenv COMMITS | jq -r "$TEMPLATE"
            printf "%s\n\n" "$(stat -c%s downloaded-exe/persian-calendar.exe) bytes"
            printf 'ðŸ“… @Persian_Calendar (win32)'
          ) | \
          jq -R --slurp --argjson mid "$MESSAGE_ID" '{
            caption: .,
            message_id: $mid,
            chat_id: "${{ secrets.TELEGRAM_CHAT_ID }}",
            parse_mode: "HTML"
          }' | \
          curl -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/editMessageCaption \
            -H 'Content-Type: application/json' \
            --data-binary @-
