name: Build EXE

permissions:
  contents: read

on: [push, workflow_dispatch]

jobs:
  upload-exe:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build EXE
        shell: cmd
        run: call "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvarsall.bat" x86 && build.bat
      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: exe
          path: persian-calendar.exe
