name: Build EXE

permissions:
  contents: read

on: [push, workflow_dispatch]

jobs:
  upload-exe:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ilammy/msvc-dev-cmd@v1
      - name: Build EXE
        shell: cmd
        run: "C:\\Program Files\\Microsoft Visual Studio\\2022\\Enterprise\\VC\\Auxiliary\\Build\\vcvarsall.bat x86 && build.bat"
      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: exe
          path: persian-calendar.exe
